import subprocess
print("== current running processes ==")
print(subprocess.run(["bash","-lc","ps -ef | grep -E 'run_assistant_axis|run_steering_test' | grep -v grep"], capture_output=True, text=True).stdout)
print("== gpu ==")
print(subprocess.run(["bash","-lc","nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv"], capture_output=True, text=True).stdout)
print("\n== latest mtimes on log files ==")
print(subprocess.run(["bash","-lc","ls -la /home/persona-vectors/logs/exp19* 2>/dev/null"], capture_output=True, text=True).stdout)
print("\n== quick_v2 log tail ==")
print(subprocess.run(["bash","-lc","tail -n 25 /home/persona-vectors/logs/exp19_gemma4_quick_v2.log 2>/dev/null"], capture_output=True, text=True).stdout)
print("\n== output_root_quick contents ==")
print(subprocess.run(["bash","-lc","find /home/persona-vectors/neurips-results/exp19/ab_project_out_allcond_quick -maxdepth 5 -type f 2>/dev/null"], capture_output=True, text=True).stdout)
print("\n== output_root (full) contents ==")
print(subprocess.run(["bash","-lc","find /home/persona-vectors/neurips-results/exp19/ab_project_out_allcond/gemma4 -maxdepth 4 -type f 2>/dev/null"], capture_output=True, text=True).stdout)
