import subprocess, time
print("== before ==")
print(subprocess.run(["bash","-lc","ps -ef | grep -E 'run_assistant_axis|run_steering_test|run_assistant_axis_causal_deconfound' | grep -v grep"], capture_output=True, text=True).stdout)
print("== kill 2305 explicitly ==")
print(subprocess.run(["bash","-lc","kill -9 2305 2>&1; sleep 3; kill -9 2305 2>&1; sleep 5"], capture_output=True, text=True).stdout)
print("== after ==")
print(subprocess.run(["bash","-lc","ps -ef | grep -E 'run_assistant_axis|run_steering_test' | grep -v grep || echo 'gemma_dead'"], capture_output=True, text=True).stdout)
print("== gpu ==")
print(subprocess.run(["bash","-lc","nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv && nvidia-smi --query-compute-apps=pid,process_name,used_memory --format=csv"], capture_output=True, text=True).stdout)
print("== gpt_oss log tail ==")
print(subprocess.run(["bash","-lc","tail -n 15 /home/persona-vectors/logs/exp19_gpt_oss_quick_final.log"], capture_output=True, text=True).stdout)
